[tool.bumper]
current_version = "0.3.0"
versioning_type = "semver"

[[tool.bumper.files]]
file = "./pyproject.toml"
search = 'version = "{current_version}"'

[[tool.bumper.files]]
file = "./wheely_bucket/__init__.py"
search = '__version__ = "{current_version}"'
